title: 我的博客
description: 个人思考与笔记
lang: zh-CN
theme: minima
markdown: kramdown
url: https://devang668.github.io
baseurl: /one-daily
kramdown:
  input: GFM
  hard_wrap: false
future: true
show_drafts: false
permalink: /:title/

github:
  repository_url: https://github.com/devang668/one-daily

exclude:
  - thoughts
  - scripts
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
